export enum RenderLogicStoreActionTypes {
  NAVIGATE_TO = 'RENDER_LOGIC_STORE-NAVIGATE_TO',
}

export const DatasetsPageActionTypes = {
  CLICK_ON_DATASET: 'DATASETS_PAGE-CLICK_ON_DATASET',
  CLICK_ON_DATASET_CATEGORY: 'DATASETS_PAGE-CLICK_ON_DATASET_TAG',
};

export const ExperimentsPageActionTypes = {
  CLICK_ON_MATCHING_SOLUTION:
    'EXPERIMENTS_PAGE-CLICK_ON_CLICK_ON_MATCHING_SOLUTION',
  DRAG_N_DROP_EXPERIMENT: 'EXPERIMENTS_PAGE-DRAG_N_DROP_EXPERIMENT',
  CLICK_ON_EXPERIMENTS_FILTER_TOOL:
    'EXPERIMENTS_PAGE-CLICK_ON_EXPERIMENTS_FILTER_TOOL',
};

export const BinaryMetricsStoreActionTypes = {
  SET_ALL_METRICS: 'BINARY_METRICS_STORE-SET_ALL_METRICS',
  SET_ALL_COUNTS: 'BINARY_METRICS_STORE-SET_ALL_COUNTS',
  CLICK_ON_PANE: 'BINARY_METRICS_STORE-CLICK_ON_PANE',
  RESET_METRICS: 'BINARY_METRICS_STORE-RESET_METRICS',
};

export const NMetricsPageActionTypes = {
  SET_ALL_METRICS: 'N_METRICS_STORE-SET_ALL_METRICS',
  INSPECT_AN_EXPERIMENT: 'N_METRICS_STORE-INSPECT_AN_EXPERIMENT',
  RESET_METRICS: 'N_METRICS_STORE-RESET_METRICS',
};

export const CoreStoreActionTypes = {
  SET_ALL_ALGORITHMS: 'CORE_STORE_ACTION-SET_ALL_ALGORITHMS',
  SET_ALL_DATASETS: 'CORE_STORE_ACTION-SET_ALL_DATASETS',
  SET_ALL_EXPERIMENTS: 'CORE_STORE-SET_ALL_EXPERIMENTS',
};
