export const ActionLogicActionTypes = {
  REGISTER_ONGOING_REQUEST: 'ACTION_LOGIC-REGISTER_ONGOING_REQUEST',
  UNREGISTER_ONGOING_REQUEST: 'ACTION_LOGIC-UNREGISTER_ONGOING_REQUEST',
  SHOW_LOADING: 'ACTION_LOGIC-SHOW_LOADING',
  HIDE_LOADING: 'ACTION_LOGIC-HIDE_LOADING',
};
