export enum CentralResourcesActionTypes {
  STORE_EXPERIMENTS = 'CENTRAL_RESOURCES-STORE_EXPERIMENTS',
  STORE_DATASETS = 'CENTRAL_RESOURCES-STORE_DATASETS',
  STORE_ALGORITHMS = 'CENTRAL_RESOURCES-STORE_ALGORITHMS',
  STORE_SIMFUNCTIONS = 'CENTRAL_RESOURCES-STORE_SIMFUNCTIONS',
}
