/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlgorithmValuesSoftKPIsInstallationCosts
 */
export interface AlgorithmValuesSoftKPIsInstallationCosts {
    /**
     * 
     * @type {string}
     * @memberof AlgorithmValuesSoftKPIsInstallationCosts
     */
    implementationKnowHowLevel?: AlgorithmValuesSoftKPIsInstallationCostsImplementationKnowHowLevelEnum;
    /**
     * 
     * @type {number}
     * @memberof AlgorithmValuesSoftKPIsInstallationCosts
     */
    timeToInstall?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlgorithmValuesSoftKPIsInstallationCosts
     */
    os?: Array<AlgorithmValuesSoftKPIsInstallationCostsOsEnum>;
}

/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsInstallationCostsImplementationKnowHowLevelEnum {
    Starter = 'starter',
    Intermediate = 'intermediate',
    Expert = 'expert'
}/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsInstallationCostsOsEnum {
    Windows = 'windows',
    Macos = 'macos',
    Linux = 'linux'
}

export function AlgorithmValuesSoftKPIsInstallationCostsFromJSON(json: any): AlgorithmValuesSoftKPIsInstallationCosts {
    return AlgorithmValuesSoftKPIsInstallationCostsFromJSONTyped(json, false);
}

export function AlgorithmValuesSoftKPIsInstallationCostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlgorithmValuesSoftKPIsInstallationCosts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'implementationKnowHowLevel': !exists(json, 'implementationKnowHowLevel') ? undefined : json['implementationKnowHowLevel'],
        'timeToInstall': !exists(json, 'timeToInstall') ? undefined : json['timeToInstall'],
        'os': !exists(json, 'os') ? undefined : json['os'],
    };
}

export function AlgorithmValuesSoftKPIsInstallationCostsToJSON(value?: AlgorithmValuesSoftKPIsInstallationCosts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'implementationKnowHowLevel': value.implementationKnowHowLevel,
        'timeToInstall': value.timeToInstall,
        'os': value.os,
    };
}


