/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlgorithmValuesSoftKPIsGeneral
 */
export interface AlgorithmValuesSoftKPIsGeneral {
    /**
     * 
     * @type {Array<string>}
     * @memberof AlgorithmValuesSoftKPIsGeneral
     */
    useCase?: Array<AlgorithmValuesSoftKPIsGeneralUseCaseEnum>;
    /**
     * 
     * @type {string}
     * @memberof AlgorithmValuesSoftKPIsGeneral
     */
    matchingSolutionType?: AlgorithmValuesSoftKPIsGeneralMatchingSolutionTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlgorithmValuesSoftKPIsGeneral
     */
    inputFormat?: Array<AlgorithmValuesSoftKPIsGeneralInputFormatEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlgorithmValuesSoftKPIsGeneral
     */
    userInterface?: Array<AlgorithmValuesSoftKPIsGeneralUserInterfaceEnum>;
    /**
     * 
     * @type {number}
     * @memberof AlgorithmValuesSoftKPIsGeneral
     */
    costs?: number;
}

/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsGeneralUseCaseEnum {
    Search = 'search',
    Deduplicate = 'deduplicate',
    Merge = 'merge'
}/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsGeneralMatchingSolutionTypeEnum {
    Ml = 'ml',
    Rulebased = 'rulebased',
    ActiveLearning = 'activeLearning',
    Other = 'other'
}/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsGeneralInputFormatEnum {
    Csv = 'csv',
    Tsv = 'tsv'
}/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsGeneralUserInterfaceEnum {
    Cli = 'cli',
    Gui = 'gui',
    Api = 'api'
}

export function AlgorithmValuesSoftKPIsGeneralFromJSON(json: any): AlgorithmValuesSoftKPIsGeneral {
    return AlgorithmValuesSoftKPIsGeneralFromJSONTyped(json, false);
}

export function AlgorithmValuesSoftKPIsGeneralFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlgorithmValuesSoftKPIsGeneral {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'useCase': !exists(json, 'useCase') ? undefined : json['useCase'],
        'matchingSolutionType': !exists(json, 'matchingSolutionType') ? undefined : json['matchingSolutionType'],
        'inputFormat': !exists(json, 'inputFormat') ? undefined : json['inputFormat'],
        'userInterface': !exists(json, 'userInterface') ? undefined : json['userInterface'],
        'costs': !exists(json, 'costs') ? undefined : json['costs'],
    };
}

export function AlgorithmValuesSoftKPIsGeneralToJSON(value?: AlgorithmValuesSoftKPIsGeneral | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'useCase': value.useCase,
        'matchingSolutionType': value.matchingSolutionType,
        'inputFormat': value.inputFormat,
        'userInterface': value.userInterface,
        'costs': value.costs,
    };
}


