/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatasetValues
 */
export interface DatasetValues {
    /**
     * 
     * @type {string}
     * @memberof DatasetValues
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetValues
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DatasetValues
     */
    numberOfRecords?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DatasetValues
     */
    tags?: Array<string>;
}

export function DatasetValuesFromJSON(json: any): DatasetValues {
    return DatasetValuesFromJSONTyped(json, false);
}

export function DatasetValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'numberOfRecords': !exists(json, 'numberOfRecords') ? undefined : json['numberOfRecords'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function DatasetValuesToJSON(value?: DatasetValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'numberOfRecords': value.numberOfRecords,
        'tags': value.tags,
    };
}


