/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExperimentConfigItem,
    ExperimentConfigItemFromJSON,
    ExperimentConfigItemFromJSONTyped,
    ExperimentConfigItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiagramExperimentItem
 */
export interface DiagramExperimentItem {
    /**
     * 
     * @type {ExperimentConfigItem}
     * @memberof DiagramExperimentItem
     */
    experiment: ExperimentConfigItem;
    /**
     * 
     * @type {ExperimentConfigItem}
     * @memberof DiagramExperimentItem
     */
    groundTruth: ExperimentConfigItem;
}

export function DiagramExperimentItemFromJSON(json: any): DiagramExperimentItem {
    return DiagramExperimentItemFromJSONTyped(json, false);
}

export function DiagramExperimentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagramExperimentItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experiment': ExperimentConfigItemFromJSON(json['experiment']),
        'groundTruth': ExperimentConfigItemFromJSON(json['groundTruth']),
    };
}

export function DiagramExperimentItemToJSON(value?: DiagramExperimentItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experiment': ExperimentConfigItemToJSON(value.experiment),
        'groundTruth': ExperimentConfigItemToJSON(value.groundTruth),
    };
}


