/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiagramCoordinates,
    DiagramCoordinatesFromJSON,
    DiagramCoordinatesFromJSONTyped,
    DiagramCoordinatesToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiagramResponse
 */
export interface DiagramResponse {
    /**
     * 
     * @type {Array<DiagramCoordinates>}
     * @memberof DiagramResponse
     */
    coordinates: Array<DiagramCoordinates>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DiagramResponse
     */
    definitionRange?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DiagramResponse
     */
    valueRange?: Array<number>;
}

export function DiagramResponseFromJSON(json: any): DiagramResponse {
    return DiagramResponseFromJSONTyped(json, false);
}

export function DiagramResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagramResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coordinates': ((json['coordinates'] as Array<any>).map(DiagramCoordinatesFromJSON)),
        'definitionRange': !exists(json, 'definitionRange') ? undefined : json['definitionRange'],
        'valueRange': !exists(json, 'valueRange') ? undefined : json['valueRange'],
    };
}

export function DiagramResponseToJSON(value?: DiagramResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coordinates': ((value.coordinates as Array<any>).map(DiagramCoordinatesToJSON)),
        'definitionRange': value.definitionRange,
        'valueRange': value.valueRange,
    };
}


