/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EffortParts
 */
export interface EffortParts {
    /**
     * 
     * @type {number}
     * @memberof EffortParts
     */
    expertise?: number;
    /**
     * 
     * @type {number}
     * @memberof EffortParts
     */
    hrAmount?: number;
}

export function EffortPartsFromJSON(json: any): EffortParts {
    return EffortPartsFromJSONTyped(json, false);
}

export function EffortPartsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffortParts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expertise': !exists(json, 'expertise') ? undefined : json['expertise'],
        'hrAmount': !exists(json, 'hrAmount') ? undefined : json['hrAmount'],
    };
}

export function EffortPartsToJSON(value?: EffortParts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expertise': value.expertise,
        'hrAmount': value.hrAmount,
    };
}


