/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._  Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentIntersectionRequestExperiments
 */
export interface ExperimentIntersectionRequestExperiments {
    /**
     * 
     * @type {number}
     * @memberof ExperimentIntersectionRequestExperiments
     */
    experimentId: number;
    /**
     * 
     * @type {boolean}
     * @memberof ExperimentIntersectionRequestExperiments
     */
    predictedCondition: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExperimentIntersectionRequestExperiments
     */
    similarityAttribute?: string;
    /**
     * 
     * @type {number}
     * @memberof ExperimentIntersectionRequestExperiments
     */
    similarityScore?: number;
}

export function ExperimentIntersectionRequestExperimentsFromJSON(json: any): ExperimentIntersectionRequestExperiments {
    return ExperimentIntersectionRequestExperimentsFromJSONTyped(json, false);
}

export function ExperimentIntersectionRequestExperimentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentIntersectionRequestExperiments {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experimentId': json['experimentId'],
        'predictedCondition': json['predictedCondition'],
        'similarityAttribute': !exists(json, 'similarityAttribute') ? undefined : json['similarityAttribute'],
        'similarityScore': !exists(json, 'similarityScore') ? undefined : json['similarityScore'],
    };
}

export function ExperimentIntersectionRequestExperimentsToJSON(value?: ExperimentIntersectionRequestExperiments | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experimentId': value.experimentId,
        'predictedCondition': value.predictedCondition,
        'similarityAttribute': value.similarityAttribute,
        'similarityScore': value.similarityScore,
    };
}


