/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExperimentValuesSoftKPIs,
    ExperimentValuesSoftKPIsFromJSON,
    ExperimentValuesSoftKPIsFromJSONTyped,
    ExperimentValuesSoftKPIsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExperimentValues
 */
export interface ExperimentValues {
    /**
     * 
     * @type {string}
     * @memberof ExperimentValues
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExperimentValues
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ExperimentValues
     */
    datasetId: number;
    /**
     * 
     * @type {number}
     * @memberof ExperimentValues
     */
    algorithmId: number;
    /**
     * 
     * @type {ExperimentValuesSoftKPIs}
     * @memberof ExperimentValues
     */
    softKPIs?: ExperimentValuesSoftKPIs;
}

export function ExperimentValuesFromJSON(json: any): ExperimentValues {
    return ExperimentValuesFromJSONTyped(json, false);
}

export function ExperimentValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'datasetId': json['datasetId'],
        'algorithmId': json['algorithmId'],
        'softKPIs': !exists(json, 'softKPIs') ? undefined : ExperimentValuesSoftKPIsFromJSON(json['softKPIs']),
    };
}

export function ExperimentValuesToJSON(value?: ExperimentValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'datasetId': value.datasetId,
        'algorithmId': value.algorithmId,
        'softKPIs': ExperimentValuesSoftKPIsToJSON(value.softKPIs),
    };
}


