/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentIntersectionPairCountsRequestExperiments
 */
export interface ExperimentIntersectionPairCountsRequestExperiments {
    /**
     * 
     * @type {number}
     * @memberof ExperimentIntersectionPairCountsRequestExperiments
     */
    experimentId: number;
    /**
     * 
     * @type {string}
     * @memberof ExperimentIntersectionPairCountsRequestExperiments
     */
    similarityAttribute?: string;
    /**
     * 
     * @type {number}
     * @memberof ExperimentIntersectionPairCountsRequestExperiments
     */
    similarityScore?: number;
}

export function ExperimentIntersectionPairCountsRequestExperimentsFromJSON(json: any): ExperimentIntersectionPairCountsRequestExperiments {
    return ExperimentIntersectionPairCountsRequestExperimentsFromJSONTyped(json, false);
}

export function ExperimentIntersectionPairCountsRequestExperimentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentIntersectionPairCountsRequestExperiments {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'experimentId': json['experimentId'],
        'similarityAttribute': !exists(json, 'similarityAttribute') ? undefined : json['similarityAttribute'],
        'similarityScore': !exists(json, 'similarityScore') ? undefined : json['similarityScore'],
    };
}

export function ExperimentIntersectionPairCountsRequestExperimentsToJSON(value?: ExperimentIntersectionPairCountsRequestExperiments | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experimentId': value.experimentId,
        'similarityAttribute': value.similarityAttribute,
        'similarityScore': value.similarityScore,
    };
}


