/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentConfigItemSimilarity
 */
export interface ExperimentConfigItemSimilarity {
    /**
     * 
     * @type {number}
     * @memberof ExperimentConfigItemSimilarity
     */
    func: number;
    /**
     * 
     * @type {number}
     * @memberof ExperimentConfigItemSimilarity
     */
    threshold: number;
}

export function ExperimentConfigItemSimilarityFromJSON(json: any): ExperimentConfigItemSimilarity {
    return ExperimentConfigItemSimilarityFromJSONTyped(json, false);
}

export function ExperimentConfigItemSimilarityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentConfigItemSimilarity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'func': json['func'],
        'threshold': json['threshold'],
    };
}

export function ExperimentConfigItemSimilarityToJSON(value?: ExperimentConfigItemSimilarity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'func': value.func,
        'threshold': value.threshold,
    };
}


