/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperimentValuesSoftKPIs
 */
export interface ExperimentValuesSoftKPIs {
    /**
     * 
     * @type {number}
     * @memberof ExperimentValuesSoftKPIs
     */
    timeToConfigure?: number;
}

export function ExperimentValuesSoftKPIsFromJSON(json: any): ExperimentValuesSoftKPIs {
    return ExperimentValuesSoftKPIsFromJSONTyped(json, false);
}

export function ExperimentValuesSoftKPIsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperimentValuesSoftKPIs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeToConfigure': !exists(json, 'timeToConfigure') ? undefined : json['timeToConfigure'],
    };
}

export function ExperimentValuesSoftKPIsToJSON(value?: ExperimentValuesSoftKPIs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeToConfigure': value.timeToConfigure,
    };
}


