/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FileResponseFormat {
    Json = 'json',
    Csv = 'csv'
}

export function FileResponseFormatFromJSON(json: any): FileResponseFormat {
    return FileResponseFormatFromJSONTyped(json, false);
}

export function FileResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileResponseFormat {
    return json as FileResponseFormat;
}

export function FileResponseFormatToJSON(value?: FileResponseFormat | null): any {
    return value as any;
}

