/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 import { exists, mapValues } from '../runtime';
 import {
     DiagramExperimentItem,
     DiagramExperimentItemFromJSON,
     DiagramExperimentItemFromJSONTyped,
     DiagramExperimentItemToJSON,
     ExperimentSimilarityConfig,
     ExperimentSimilarityConfigFromJSON,
     ExperimentSimilarityConfigFromJSONTyped,
     ExperimentSimilarityConfigToJSON,
 } from './';
 
 /**
  * 
  * @export
  * @interface InlineObject
  */
 export interface InlineObject {
     /**
      * 
      * @type {Array<DiagramExperimentItem>}
      * @memberof InlineObject
      */
     multipleExperiments?: Array<DiagramExperimentItem>;
     /**
      * 
      * @type {ExperimentSimilarityConfig}
      * @memberof InlineObject
      */
     similarityThresholds?: ExperimentSimilarityConfig;
 }
 
 export function InlineObjectFromJSON(json: any): InlineObject {
     return InlineObjectFromJSONTyped(json, false);
 }
 
 export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
     if ((json === undefined) || (json === null)) {
         return json;
     }
     return {
         
         'multipleExperiments': !exists(json, 'multipleExperiments') ? undefined : ((json['multipleExperiments'] as Array<any>).map(DiagramExperimentItemFromJSON)),
         'similarityThresholds': !exists(json, 'similarityThresholds') ? undefined : ExperimentSimilarityConfigFromJSON(json['similarityThresholds']),
     };
 }
 
 export function InlineObjectToJSON(value?: InlineObject | null): any {
     if (value === undefined) {
         return undefined;
     }
     if (value === null) {
         return null;
     }
     return {
         
         'multipleExperiments': value.multipleExperiments === undefined ? undefined : ((value.multipleExperiments as Array<any>).map(DiagramExperimentItemToJSON)),
         'similarityThresholds': ExperimentSimilarityConfigToJSON(value.similarityThresholds),
     };
 }
 
 
 