/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SimilarityThresholdFunctionAllOf,
    SimilarityThresholdFunctionAllOfFromJSON,
    SimilarityThresholdFunctionAllOfFromJSONTyped,
    SimilarityThresholdFunctionAllOfToJSON,
    SimilarityThresholdFunctionDefinition,
    SimilarityThresholdFunctionDefinitionFromJSON,
    SimilarityThresholdFunctionDefinitionFromJSONTyped,
    SimilarityThresholdFunctionDefinitionToJSON,
    SimilarityThresholdFunctionValues,
    SimilarityThresholdFunctionValuesFromJSON,
    SimilarityThresholdFunctionValuesFromJSONTyped,
    SimilarityThresholdFunctionValuesToJSON,
} from './';

/**
 * 
 * @export
 * @interface SimilarityThresholdFunction
 */
export interface SimilarityThresholdFunction {
    /**
     * 
     * @type {number}
     * @memberof SimilarityThresholdFunction
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SimilarityThresholdFunction
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SimilarityThresholdFunction
     */
    experimentId: number;
    /**
     * 
     * @type {SimilarityThresholdFunctionDefinition}
     * @memberof SimilarityThresholdFunction
     */
    definition: SimilarityThresholdFunctionDefinition;
}

export function SimilarityThresholdFunctionFromJSON(json: any): SimilarityThresholdFunction {
    return SimilarityThresholdFunctionFromJSONTyped(json, false);
}

export function SimilarityThresholdFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilarityThresholdFunction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'experimentId': json['experimentId'],
        'definition': SimilarityThresholdFunctionDefinitionFromJSON(json['definition']),
    };
}

export function SimilarityThresholdFunctionToJSON(value?: SimilarityThresholdFunction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'experimentId': value.experimentId,
        'definition': SimilarityThresholdFunctionDefinitionToJSON(value.definition),
    };
}


