/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SimilarityThresholdFunctionValues,
    SimilarityThresholdFunctionValuesFromJSON,
    SimilarityThresholdFunctionValuesFromJSONTyped,
    SimilarityThresholdFunctionValuesToJSON,
} from './';

/**
 * 
 * @export
 * @interface SimilarityThresholdOperator
 */
export interface SimilarityThresholdOperator {
    /**
     * 
     * @type {SimilarityThresholdFunctionValues}
     * @memberof SimilarityThresholdOperator
     */
    left: SimilarityThresholdFunctionValues;
    /**
     * 
     * @type {SimilarityThresholdFunctionValues}
     * @memberof SimilarityThresholdOperator
     */
    right: SimilarityThresholdFunctionValues;
    /**
     * 
     * @type {string}
     * @memberof SimilarityThresholdOperator
     */
    operator: SimilarityThresholdOperatorOperatorEnum;
}

/**
* @export
* @enum {string}
*/
export enum SimilarityThresholdOperatorOperatorEnum {
    Add = 'ADD',
    Subtract = 'SUBTRACT',
    Multiply = 'MULTIPLY',
    Divide = 'DIVIDE'
}

export function SimilarityThresholdOperatorFromJSON(json: any): SimilarityThresholdOperator {
    return SimilarityThresholdOperatorFromJSONTyped(json, false);
}

export function SimilarityThresholdOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimilarityThresholdOperator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'left': SimilarityThresholdFunctionValuesFromJSON(json['left']),
        'right': SimilarityThresholdFunctionValuesFromJSON(json['right']),
        'operator': json['operator'],
    };
}

export function SimilarityThresholdOperatorToJSON(value?: SimilarityThresholdOperator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'left': SimilarityThresholdFunctionValuesToJSON(value.left),
        'right': SimilarityThresholdFunctionValuesToJSON(value.right),
        'operator': value.operator,
    };
}


