export enum SelectableInputActionTypes {
  SHOW_POPOVER = 'SELECTABLE_INPUT-SHOW_POPOVER',
  CLOSE_POPOVER = 'SELECTABLE_INPUT-CLOSE_POPOVER',
  CHANGE_SEARCH_STRING = 'SELECTABLE_INPUT-CHANGE_SEARCH_STRING',
  RESET_COMPONENT = 'SELECTABLE_INPUT-RESET_COMPONENT',
}
