export enum BenchmarkAppActionsTypes {
  SET_EXPERIMENTS = 'BenchmarkAppActionsTypes-SET_EXPERIMENTS',
  SET_DATASETS = 'BenchmarkAppActionsTypes-SET_DATASETS',
  SET_ALGORITHMS = 'BenchmarkAppActionsTypes-SET_ALGORITHMS',
  TOGGLE_EXPERIMENT = 'BenchmarkAppActionsTypes-TOGGLE_EXPERIMENT',
  SELECT_NONE = 'BenchmarkAppActionsTypes-SELECT_NONE',
  EXPAND_DATASET = 'BenchmarkAppActionsTypes-EXPAND_DATASET',
  EXPAND_DATASET_FULL = 'BenchmarkAppActionsTypes-EXPAND_DATASET_FULL',
  SHRINK_DATASET = 'BenchmarkAppActionsTypes-SHRINK_DATASET',
  EXPAND_ALGORITHM = 'BenchmarkAppActionsTypes-EXPAND_ALGORITHM',
  SHRINK_ALGORITHM = 'BenchmarkAppActionsTypes-SHRINK_ALGORITHM',
  SELECT_DATASET_CHILDREN = 'BenchmarkAppActionsTypes-SELECT_DATASET_CHILDREN',
  SELECT_ALGORITHM_CHILDREN = 'BenchmarkAppActionsTypes-SELECT_ALGORITHM_CHILDREN',
  SET_SEARCH_STRING = 'BenchmarkAppActionsTypes-SET_SEARCH_STRING',
  OPEN_STRATEGY = 'BenchmarkAppActionsTypes-OPEN_STRATEGY',
}
