export enum ConfigurationStoreActionTypes {
  SET_DATASET_SELECTION = 'ConfigurationStoreActionTypes-SET_DATASET_SELECTION',
  SET_MATCHING_SOLUTION_SELECTION = 'ConfigurationStoreActionTypes-SET_MATCHING_SOLUTION_SELECTION',
  SET_EXPERIMENT_SELECTION = 'ConfigurationStoreActionTypes-SET_EXPERIMENT_SELECTION',
  SET_FUNCTION_SELECTION = 'ConfigurationStoreActionTypes-SET_FUNCTION_SELECTION',
  SET_THRESHOLD_SELECTION = 'ConfigurationStoreActionTypes-SET_THRESHOLD_SELECTION',
}
