export enum ConfigurationStoreActionTypes {
  SET_DATASET_SELECTION = 'ConfigurationStoreActionTypes-SET_DATASET_SELECTION',
  SET_ALGORITHM_SELECTION = 'ConfigurationStoreActionTypes-SET_ALGORITHM_SELECTION',
  SET_EXPERIMENT_SELECTION = 'ConfigurationStoreActionTypes-SET_EXPERIMENT_SELECTION',
  SET_SIM_FUNCTION_SELECTION = 'ConfigurationStoreActionTypes-SET_SIM_FUNCTION_SELECTION',
  SET_SIM_THRESHOLD_SELECTION = 'ConfigurationStoreActionTypes-SET_SIM_THRESHOLD_SELECTION',
}
