export enum DatasetDialogActionTypes {
  CHANGE_DATASET_NAME = 'DATASET_DIALOG-CHANGE_DATASET_NAME',
  CHANGE_DATASET_DESCRIPTION = 'DATASET_DIALOG-CHANGE_DATASET_DESCRIPTION',
  CHANGE_DATASET_TYPE = 'DATASET_DIALOG-CHANGE_DATASET_TYPE',
  CHANGE_DATASET_FILES = 'DATASET_DIALOG-CHANGE_DATASET_FILES',
  CHANGE_DATASET_LENGTH = 'DATASET_DIALOG-CHANGE_DATASET_LENGTH',
  CHANGE_CSV_ID_COLUMN = 'DATASET_DIALOG-CHANGE_CSV_ID_COLUMN',
  CHANGE_CSV_SEPARATOR = 'DATASET_DIALOG-CHANGE_CSV_SEPARATOR',
  CHANGE_CSV_QUOTE = 'DATASET_DIALOG-CHANGE_CSV_QUOTE',
  CHANGE_CSV_ESCAPE = 'DATASET_DIALOG-CHANGE_CSV_ESCAPE',
  CHANGE_TAGS = 'DATASET_DIALOG-CHANGE_TAGS',
  RESET_DIALOG = 'DATASET_DIALOG-RESET_DIALOG',
  PREFILL_DIALOG = 'DATASET_DIALOG-PREFILL_DIALOG',
}
