export enum ViewIDs {
  AboutApp,
  DatasetsApp,
  ExperimentsApp,
  AlgorithmsApp,
  BINARY_METRICS,
  N_METRICS,
  INTERSECTION,
  BenchmarkApp,
  STANDALONE_DATA_VIEWER,
  AlgorithmDialog,
  DatasetDialog,
  ExperimentDialog,
  PreviewDialog,
}
