export enum ViewIDs {
  AboutApp,
  DatasetsApp,
  ExperimentsApp,
  AlgorithmsApp,
  BINARY_METRICS,
  N_METRICS,
  INTERSECTION,
  BenchmarkApp,
  DataViewerApp,
  AlgorithmDialog,
  DatasetDialog,
  ExperimentDialog,
  PreviewDialog,
  SimilarityFuncsDialog,
}
