/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research.  With snowman, developers and researchers will be able to compare the performance of different data matching  solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AlgorithmValuesSoftKPIs
 */
export interface AlgorithmValuesSoftKPIs {
    /**
     * 
     * @type {string}
     * @memberof AlgorithmValuesSoftKPIs
     */
    implementationKnowHowLevel?: AlgorithmValuesSoftKPIsImplementationKnowHowLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof AlgorithmValuesSoftKPIs
     */
    matchingSolutionType?: AlgorithmValuesSoftKPIsMatchingSolutionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AlgorithmValuesSoftKPIs
     */
    timeToInstall?: number;
    /**
     * 
     * @type {number}
     * @memberof AlgorithmValuesSoftKPIs
     */
    timeToConfigure?: number;
}

/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsImplementationKnowHowLevelEnum {
    Starter = 'starter',
    Intermediate = 'intermediate',
    Expert = 'expert'
}
/**
* @export
* @enum {string}
*/
export enum AlgorithmValuesSoftKPIsMatchingSolutionTypeEnum {
    Ml = 'ml',
    Rulebased = 'rulebased',
    Other = 'other'
}