/* tslint:disable */
/* eslint-disable */
/**
 * Snowman API
 * _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: snowman@groups.sap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SimilarityThresholdFunctionDefinition,
} from './';

/**
 * 
 * @export
 * @interface SimilarityThresholdFunctionOperator
 */
export interface SimilarityThresholdFunctionOperator {
    /**
     * 
     * @type {SimilarityThresholdFunctionDefinition}
     * @memberof SimilarityThresholdFunctionOperator
     */
    left: SimilarityThresholdFunctionDefinition;
    /**
     * 
     * @type {SimilarityThresholdFunctionDefinition}
     * @memberof SimilarityThresholdFunctionOperator
     */
    right: SimilarityThresholdFunctionDefinition;
    /**
     * 
     * @type {string}
     * @memberof SimilarityThresholdFunctionOperator
     */
    operator: SimilarityThresholdFunctionOperatorOperatorEnum;
}

/**
* @export
* @enum {string}
*/
export enum SimilarityThresholdFunctionOperatorOperatorEnum {
    Add = 'ADD',
    Subtract = 'SUBTRACT',
    Multiply = 'MULTIPLY',
    Divide = 'DIVIDE',
    Power = 'POWER',
    Pow = 'POW',
    Atan2 = 'ATAN2',
    Log = 'LOG',
    Mod = 'MOD'
}