export enum FunctionBuilderDialogActionTypes {
  SELECT_ROOT_TYPE = 'FUNCTION_BUILDER_DIALOG-SELECT_ROOT_TYPE',
  REGISTER_BUILDING_BLOCK = 'FUNCTION_BUILDER_DIALOG-REGISTER_BUILDING_BLOCK',
  UNREGISTER_BUILDING_BLOCK = 'FUNCTION_BUILDER_DIALOG-UNREGISTER_BUILDING_BLOCK',
  CHOOSE_STRATEGY = 'FUNCTION_BUILDER_DIALOG-CHOOSE_STRATEGY',
}
