export enum FunctionBuilderDialogActionTypes {
  RESET_DIALOG = 'FUNCTION_BUILDER_DIALOG-RESET_DIALOG',
  REGISTER_BUILDING_BLOCK = 'FUNCTION_BUILDER_DIALOG-REGISTER_BUILDING_BLOCK',
  UNREGISTER_BUILDING_BLOCK = 'FUNCTION_BUILDER_DIALOG-UNREGISTER_BUILDING_BLOCK',
  REGISTER_NEW_ACCESS_KEY = 'FUNCTION_BUILDER_DIALOG-REGISTER_NEW_ACCESS_KEY',
  CHOOSE_STRATEGY = 'FUNCTION_BUILDER_DIALOG-CHOOSE_STRATEGY',
  SET_LEFT_VALUE = 'FUNCTION_BUILDER_DIALOG-SET_LEFT_VALUE',
  SET_RIGHT_VALUE = 'FUNCTION_BUILDER_DIALOG-SET_RIGHT_VALUE',
  SET_MID_VALUE = 'FUNCTION_BUILDER_DIALOG-SET_MID_VALUE',
  CHANGE_FUNCTION_NAME = 'FUNCTION_BUILDER_DIALOG-CHANGE_FUNCTION_NAME',
  LOAD_EXPERIMENT_COLUMNS = 'FUNCTION_BUILDER_DIALOG-LOAD_EXPERIMENT_COLUMNS',
  SUBSTITUTE_RESERVED_ACCESS_KEYS = 'FUNCTION_BUILDER_DIALOG-SUBSTITUTE_RESERVED_ACCESS_KEYS',
  SUBSTITUTE_FUNCTION_BUILDING_BLOCK = 'FUNCTION_BUILDER_DIALOG-SUBSTITUTE_FUNCTION_BUILDING_BLOCK',
}
