export enum InputChipActionTypes {
  SHOW_INPUT = 'INPUT_CHIP-SHOW_INPUT',
  HIDE_INPUT = 'INPUT_CHIP-HIDE_INPUT',
  CHANGE_VALUE = 'INPUT_CHIP-CHANGE_VALUE',
  RESET_INPUT = 'INPUT_CHIP-RESET_INPUT',
}
