export enum SimilarityFuncsDialogActionTypes {
  CHANGE_SEARCH_STRING = 'SIMILARITY_FUNCS_DIALOG-CHANGE_SEARCH_STRING',
  LOAD_SIMILARITY_FUNCTIONS = 'SIMILARITY_FUNCS_DIALOG-LOAD_SIMILARITY_FUNCTIONS',
}
