export enum SimilarityFuncsDialogActionTypes {
  RESET_DIALOG = 'SimilarityFuncsDialogActionTypes-RESET_DIALOG',
  CHANGE_SEARCH_STRING = 'SIMILARITY_FUNCS_DIALOG-CHANGE_SEARCH_STRING',
  LOAD_SIMILARITY_FUNCTIONS = 'SIMILARITY_FUNCS_DIALOG-LOAD_SIMILARITY_FUNCTIONS',
}
