export enum AlgorithmDialogActionTypes {
  CHANGE_ALGORITHM_NAME = 'ALGORITHM_DIALOG-CHANGE_ALGORITHM_NAME',
  CHANGE_ALGORITHM_DESCRIPTION = 'ALGORITHM_DIALOG-CHANGE_ALGORITHM_DESCRIPTION',
  RESET_DIALOG = 'ALGORITHM_DIALOG-RESET_DIALOG',
}
