export enum AlgorithmDialogActionTypes {
  CHANGE_ALGORITHM_NAME = 'ALGORITHM_DIALOG-CHANGE_ALGORITHM_NAME',
  CHANGE_ALGORITHM_DESCRIPTION = 'ALGORITHM_DIALOG-CHANGE_ALGORITHM_DESCRIPTION',
  CHANGE_INTEGRATION_INSTALLATION_EFFORT = 'ALGORITHM_DIALOG-CHANGE_INTEGRATION_INSTALLATION_EFFORT',
  CHANGE_INTEGRATION_DEPLOYMENT_TYPE = 'ALGORITHM_DIALOG-CHANGE_INTEGRATION_DEPLOYMENT_TYPE',
  CHANGE_INTEGRATION_SOLUTION_TYPE = 'ALGORITHM_DIALOG-CHANGE_INTEGRATION_SOLUTION_TYPE',
  CHANGE_INTEGRATION_USE_CASE = 'ALGORITHM_DIALOG-CHANGE_INTEGRATION_USE_CASE',
  CHANGE_INTEGRATION_GENERAL_COSTS = 'ALGORITHM_DIALOG-CHANGE_INTEGRATION_GENERAL_COSTS',
  CHANGE_CONFIGURATION_MATCHING_SOLUTION_EFFORT = 'ALGORITHM_DIALOG-CHANGE_CONFIGURATION_MATCHING_SOLUTION_EFFORT',
  CHANGE_CONFIGURATION_DOMAIN_EFFORT = 'ALGORITHM_DIALOG-CHANGE_CONFIGURATION_DOMAIN_EFFORT',
  CHANGE_CONFIGURATION_INTERFACES = 'ALGORITHM_DIALOG-CHANGE_CONFIGURATION_INTERFACES',
  CHANGE_CONFIGURATION_SUPPORTED_OSS = 'ALGORITHM_DIALOG-CHANGE_CONFIGURATION_SUPPORTED_OSS',
  RESET_DIALOG = 'ALGORITHM_DIALOG-RESET_DIALOG',
}
