export enum AlgorithmSegmentTypeEnum {
  INTEGRATION_EFFORT = 'INTEGRATION_EFFORT',
  CONFIGURATION_EFFORT = 'CONFIGURATION_EFFORT',
  ENVIRONMENT_KPIS = 'ENVIRONMENT_KPIS',
  OTHER_KPIS = 'OTHER_KPIS',
}
