import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import * as OpenApiValidator from 'express-openapi-validator';
import http from 'http';
import { join } from 'path';
import path from 'path';

import { HOST, OPENAPI_YAML_PATH, PORT } from '../config';
import { identifyResponse } from './identifyResponse';

export class ExpressServer {
  private readonly host: string = HOST;
  private readonly port: number = PORT;
  private readonly openApiPath: string = OPENAPI_YAML_PATH;
  private app: express.Express;
  private server: http.Server | undefined;
  constructor() {
    this.app = express();
    this.setupMiddleware();
  }

  setupMiddleware(): void {
    this.app.use(cors());
    this.app.use(express.json({ limit: '14MB' }));
    this.app.use(express.urlencoded({ extended: false }));
    this.app.use(cookieParser());
    //Send the openapi document *AS GENERATED BY THE GENERATOR*
    this.app.get('/openapi', (req: express.Request, res: express.Response) =>
      res.sendFile(this.openApiPath)
    );
    this.app.get('/api', (_req: express.Request, res: express.Response) => {
      res.status(200).send('Snowman API');
    });
    this.app.get(
      '/api/identify',
      (_req: express.Request, res: express.Response) => {
        res.status(200).send(identifyResponse);
      }
    );
    this.app.use('/', express.static(join(__dirname, '../../../', 'app')));
  }

  launch(): void {
    this.app.use(
      OpenApiValidator.middleware({
        apiSpec: this.openApiPath,
        operationHandlers: path.join(__dirname),
      })
    );

    // eslint-disable-next-line no-unused-vars
    this.app.use(
      (
        err: { status: number; message?: string; errors?: string },
        req: express.Request,
        res: express.Response,
        next: express.NextFunction
      ) => {
        // format errors
        res.status(err.status || 500).json({
          message: err.message || err,
          errors: err.errors || '',
        });
      }
    );
    this.app.use((_req, res) => {
      // Route everything that's remaining to index.html
      res.sendFile(join(__dirname, '../../../', 'app', 'index.html'));
    });
    this.server = http.createServer(this.app).listen(this.port, this.host);
  }

  close(): void {
    if (this.server !== undefined) {
      this.server.close();
    }
  }

  static async launch(): Promise<void> {
    const expressServer = new ExpressServer();
    try {
      expressServer.launch();
    } catch (error) {
      expressServer.close();
      throw error;
    }
  }
}
