export enum ExperimentDialogActionTypes {
  CHANGE_EXPERIMENT_NAME = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_NAME',
  CHANGE_EXPERIMENT_DESCRIPTION = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_DESCRIPTION',
  CHANGE_EXPERIMENT_FORMAT = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_FORMAT',
  CHANGE_SELECTED_FILES = 'EXPERIMENT_DIALOG-CHANGE_SELECTED_FILES',
  RESET_DIALOG = 'EXPERIMENT_DIALOG-RESET_DIALOG',
  CLICK_ON_MATCHING_SOLUTION_TAG = 'EXPERIMENT_DIALOG-CLICK_ON_MATCHING_SOLUTION_TAG',
  PREFILL_DIALOG = 'EXPERIMENT_DIALOG-PREFILL_DIALOG',
}
