export enum ExperimentDialogActionTypes {
  CHANGE_EXPERIMENT_NAME = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_NAME',
  CHANGE_EXPERIMENT_DESCRIPTION = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_DESCRIPTION',
  CHANGE_EXPERIMENT_FORMAT = 'EXPERIMENT_DIALOG-CHANGE_EXPERIMENT_FORMAT',
  CHANGE_SELECTED_FILES = 'EXPERIMENT_DIALOG-CHANGE_SELECTED_FILES',
  RESET_DIALOG = 'EXPERIMENT_DIALOG-RESET_DIALOG',
  CHANGE_ALGORITHM = 'EXPERIMENT_DIALOG-CHANGE_ALGORITHM',
  CHANGE_DATASET = 'EXPERIMENT_DIALOG-CHANGE_DATASET',
  PREFILL_DIALOG = 'EXPERIMENT_DIALOG-PREFILL_DIALOG',
}
